var emojiDictionary = {
    "😊": "Muskaan wala chehra muskaan wali aankhon ke saath",
    "😂": "Hasi ke saath aankhon se aansoo",
    "❤️": "Laal dil",
    "👍": "Ungliyon ka thumbs up",
    "👌": "Theek hai haath",
    "😍": "Muskaan wala chehra dil ke saath",
    "🙌": "Haath upar uthane wala",
    "🎉": "Party ka popper",
    "😎": "Muskaan wala chehra sunglasses ke saath",
    "💪": "Majboot biceps",
    "🔥": "Aag",
    "🌟": "Chamak",
    "🎈": "Balloon",
    "💼": "Briefcase",
    "🍔": "Hamburger",
    "🍕": "Pizza",
    "🍦": "Ice cream",
    "🍎": "Laal seb",
    "🍉": "Tarbooz",
    "🎸": "Guitar",
    "🎮": "Video game",
    "⚽": "Football",
    "🏀": "Basketball",
    "🏆": "Trophy",
    "🚀": "Rocket",
    "🌈": "Rainbow",
    "🎨": "Artist ka palette",
    "📚": "Books",
    "💡": "Bulb",
    "🔑": "Chabi",
    "💖": "Chamakta dil",
    "💫": "Chakkar",
    "🌞": "Chehra ke saath sooraj",
    "🌛": "Teekhi chaand ki raat",
    "🌺": "Hibiscus",
    "🌼": "Blossom",
    "🍀": "Chaar patti ka patte",
    "🍄": "Mushroom",
    "🌋": "Jwala mukhi",
    "🌠": "Chamakta sitara",
    "🎊": "Confetti ball",
    "🎁": "Wrapped gift",
    "🎂": "Birthday cake",
    "🍰": "Shortcake",
    "🍹": "Tropical drink",
    "🍭": "Lollipop",
    "🍬": "Candy",
    "🍧": "Shaved ice",
    "🍨": "Ice cream",
    "🍩": "Doughnut",
    "🍪": "Cookie",
    "🍫": "Chocolate bar",
    "🍯": "Honey pot",
    "🍓": "Strawberry",
    "🍇": "Grapes",
    "🍒": "Cherries",
    "🍍": "Pineapple",
    "🍌": "Banana",
    "🍋": "Lemon",
    "🥝": "Kiwi fruit",
    "🥥": "Coconut",
    "🥑": "Avocado",
    "🥒": "Cucumber",
    "🥦": "Broccoli",
    "🥕": "Carrot",
    "🥔": "Potato",
    "🥖": "Baguette bread",
    "🥐": "Croissant",
    "🥨": "Pretzel",
    "🥞": "Pancakes",
    "🍳": "Cooking",
    "🥓": "Bacon",
    "🥩": "Steak",
    "🍗": "Poultry leg",
    "🍖": "Meat on bone",
    "🥪": "Sandwich",
    "🌮": "Taco",
    "🌯": "Burrito",
    "🥙": "Stuffed flatbread",
    "🥚": "Egg",
    "🍟": "French fries",
    "🥗": "Green salad",
    "🍝": "Spaghetti",
    "🍜": "Steaming bowl",
    "🍲": "Pot of food",
    "🍛": "Curry rice",
    "🍣": "Sushi",
    "🍱": "Bento box",
    "🍤": "Fried shrimp",
    "🍙": "Rice ball",
    "🍚": "Cooked rice",
    "🍘": "Rice cracker",
    "🍥": "Fish cake",
    "🥮": "Moon cake",
    "🍢": "Oden",
    "🍡": "Dango",
    "🥧": "Pie",
    "🧁": "Cupcake",
    "🥠": "Fortune cookie",
    "🍮": "Custard",
    "🍼": "Baby bottle",
    "🥛": "Glass of milk",
    "😀": "Haste hue chehra",
    "😃": "Bade aankhon wala haste hue chehra",
    "😄": "Muskaan wala chehra muskurane wali aankhon ke saath",
    "😁": "Aankhon se muskurane wala chehra",
    "😆": "Muskarate hue chehra aankhon ko chhipa kar",
    "😅": "Paseene wale chehre ke saath muskurahat",
    "🤣": "Floor par hasne wala",
    "😇": "Muskaan wala chehra halki chamak ke saath",
    "🙂": "Thoda muskurane wala chehra",
    "🙃": "Ulta chehra",
    "😉": "Ankhen chura kar muskurane wala chehra",
    "😌": "Chain ki saans lene wala chehra",
    "😘": "Chehre ko kiss de raha chehra",
    "😗": "Chumban dene wala chehra",
    "😙": "Kissing Face with Smiling Eyes",
    "😚": "Kissing Face with Closed Eyes",
    "😋": "Face Savoring Food",
    "😛": "Face with Tongue",
    "😜": "Winking Face with Tongue",
    "😝": "Squinting Face with Tongue",
    "🤑": "Money-Mouth Face",
    "🤗": "Hugging Face",
    "🤓": "Nerd Face",
    "🤡": "Clown Face",
    "🤠": "Cowboy Hat Face",
    "😏": "Smirking Face",
    "😒": "Unamused Face",
    "😞": "Disappointed Face",
    "😔": "Pensive Face",
    "😟": "Worried Face",
    "😕": "Confused Face",
    "🙁": "Thoda udaas chehra",
    "☹️": "Frowning Face",
    "😣": "Persevering Face",
    "😖": "Confounded Face",
    "😫": "Thaka hua chehra",
    "😩": "Thak gaya chehra",
    "😤": "Face with Steam From Nose",
    "😠": "Gusse wala chehra",
    "😡": "Gusse wala chehra",
    "😶": "Chehre ke saath mooh nahi",
    "😐": "Nirdosh chehra",
    "😑": "Vyaktiheen chehra",
    "😯": "Chup sa chehra",
    "😦": "Mooh khol ke udaas chehra",
    "😧": "Pareeshaan chehra",
    "😮": "Khule muh wala chehra",
    "😲": "Hairat wala chehra",
    "😵": "Dizzy Face",
    "😳": "Flushed Face",
    "😱": "Dar se cheekhne wala chehra",
    "😨": "Bhayankar chehra",
    "😰": "Paseena chehre ke saath chintit",
    "😢": "Roye hue chehra",
    "😥": "Khushi ke saath udaas chehra",
    "🤤": "Thook wala chehra",
    "😭": "Zor se roya chehra",
    "😓": "Niche dekhte hue chehra",
    "😪": "Sone wala chehra",
    "😴": "Nind wala chehra",
    "🙄": "Ghoomte hue aankhon wala chehra",
    "🤔": "Sochne wala chehra",
    "🤥": "Jhoot bolne wala chehra",
    "😬": "Muskarate hue chehre ke saath chehra",
    "🤐": "Zipper-Mouth Face",
    "🤢": "Nauseated Face",
    "🤮": "Face Vomiting",
    "🤧": "Chheenkne wala chehra",
    "😷": "Face with Medical Mask",
    "🤒": "Face with Thermometer",
    "🤕": "Face with Head-Bandage",
    "🤖": "Robot Face",
    "😺": "Smiling Cat Face",
    "😸": "Grinning Cat Face",
    "😹": "Cat Face with Tears of Joy",
    "😻": "Smiling Cat Face with Heart-Eyes",
    "😼": "Cat Face with Wry Smile",
    "😽": "Kissing Cat Face",
    "🙀": "Weary Cat Face",
    "😿": "Crying Cat Face",
    "😾": "Pouting Cat Face",
    "👶": "Baby",
    "👦": "Ladka",
    "👧": "Ladki",
    "🧑": "Vyakti",
    "👨": "Aadmi",
    "👩": "Aurat",
    "👴": "Buddha Aadmi",
    "👵": "Buddhi Aurat",
    "👨‍⚕️": "Aadmi Health Worker",
    "👩‍⚕️": "Aurat Health Worker",
    "👨‍🎓": "Aadmi Student",
    "👩‍🎓": "Aurat Student",
    "👨‍🏫": "Aadmi Teacher",
    "👩‍🏫": "Aurat Teacher",
    "👨‍⚖️": "Aadmi Judge",
    "👩‍⚖️": "Aurat Judge",
    "👨‍🌾": "Aadmi Kisaan",
    "👩‍🌾": "Aurat Kisaan",
    "👨‍🍳": "Aadmi Cook",
    "👩‍🍳": "Aurat Cook",
    "👨‍🔧": "Aadmi Mechanic",
    "👩‍🔧": "Aurat Mechanic",
    "👨‍🏭": "Aadmi Factory Worker",
    "👩‍🏭": "Aurat Factory Worker",
    "👨‍💼": "Aadmi Office Worker",
    "👩‍💼": "Aurat Office Worker",
    "👨‍🔬": "Aadmi Scientist",
    "👩‍🔬": "Aurat Scientist",
    "👨‍💻": "Aadmi Technologist",
    "👩‍💻": "Aurat Technologist",
    "👨‍🎤": "Aadmi Singer",
    "👩‍🎤": "Aurat Singer",
    "👨‍🎨": "Aadmi Artist",
    "👩‍🎨": "Aurat Artist",
    "👨‍✈️": "Aadmi Pilot",
    "🌴": "Nariyal ka ped",
    "🌵": "Cactus",
    "🌾": "Anaj",
    "🌿": "Herb",
    "☘️": "Shamrock",
    "🍀": "Charan patti",
    "🍁": "Maple Leaf",
    "🍂": "Girte hue patte",
    "🍃": "Hawa me fluttering patta",
    "🍄": "Mushroom",
    "🌰": "Chestnut",
    "🦀": "Crab",
    "🦞": "Lobster",
    "🦐": "Shrimp",
    "🦑": "Squid",
    "🌍": "Europe-Africa dikhane wala globe",
    "🌎": "Americas dikhane wala globe",
    "🌏": "Asia-Australia dikhane wala globe",
    "🌐": "Dikhane wala globe with meridians",
    "🗺️": "Duniya ka nakshe",
    "🗾": "Japan ka nakshe",
    "🧭": "Compass",
    "🏔️": "Snow-Capped Mountain",
    "⛰️": "Mountain",
    "🌋": "Volcano",
    "🗻": "Mount Fuji",
    "🏕️": "Camping",
    "🏖️": "Beach with Umbrella",
    "🏜️": "Desert",
    "🏝️": "Desert Island",
    "🏞️": "National Park",
    "🏟️": "Stadium",
    "🏛️": "Classical Building",
    "🏗️": "Building Construction",
    "🧱": "Brick",
    "🏘️": "Houses",
    "🏚️": "Derelict House",
    "🏠": "House",
    "🏡": "House with Garden",
    "🏢": "Office Building",
    "🏣": "Japanese Post Office",
    "🏤": "Post Office",
    "🏥": "Hospital",
    "🏦": "Bank",
    "🏨": "Hotel",
    "🏩": "Love Hotel",
    "🏪": "Convenience Store",
    "🏫": "School",
    "🏬": "Department Store",
    "🏭": "Factory",
    "🏯": "Japanese Castle",
    "🏰": "Castle",
    "💒": "Wedding",
    "🗼": "Tokyo Tower",
    "🗽": "Statue of Liberty",
    "⛪": "Church",
    "🕌": "Masjid",
    "🕍": "Synagogue",
    "⛩️": "Shinto Shrine",
    "🕋": "Kaaba",
    "⛲": "Fountain",
    "⛺": "Tent",
    "🌁": "Foggy",
    "🌃": "Night with Stars",
    "🏙️": "Cityscape",
    "🌄": "Sunrise Over Mountains",
    "🌅": "Sunrise",
    "🌆": "Cityscape at Dusk",
    "🌇": "Sunset",
    "🌉": "Bridge at Night",
    "♨️": "Hot Springs",
    "🎠": "Carousel Horse",
    "🎡": "Ferris Wheel",
    "🎢": "Roller Coaster",
    "💈": "Barber Pole",
    "🎪": "Circus Tent",
    "🚂": "Steam Locomotive",
    "🚃": "Railway Car",
    "🚄": "High-Speed Train",
    "🚅": "Bullet Train",
    "🚆": "Train",
    "🚇": "Metro",
    "🚈": "Light Rail",
    "🚉": "Station",
    "🚊": "Tram",
    "🚝": "Monorail",
    "🚞": "Mountain Railway",
    "🚋": "Tram Car",
    "🚌": "Bus",
    "🚍": "Oncoming Bus",
    "🚎": "Trolleybus",
    "🚐": "Minibus",
    "🚑": "Ambulance",
    "🚒": "Fire Engine",
    "🚓": "Police Car",
    "🚔": "Oncoming Police Car",
    "🚕": "Taxi",
    "🚖": "Oncoming Taxi",
    "🚗": "Automobile",
    "🚘": "Oncoming Automobile",
    "🚙": "Sport Utility Vehicle",
    "🚚": "Delivery Truck",
    "🚛": "Articulated Lorry",
    "🚜": "Tractor",
    "🏎️": "Racing Car",
    "🛵": "Motor Scooter",
    "🛺": "Auto Rickshaw",
    "🚲": "Bicycle",
    "🛴": "Kick Scooter",
    "🛹": "Skateboard",
    "🚏": "Bus Stop",
    "🛣️": "Motorway",
    "🛤️": "Railway Track",
    "🛢️": "Oil Drum",
    "⛽": "Fuel Pump",
    "🚨": "Police Car Light",
    "🚥": "Horizontal Traffic Light",
    "🚦": "Vertical Traffic Light",
    "🛑": "Stop Sign",
    "🚧": "Construction",
    "⚓": "Anchor",
    "⛵": "Sailboat",
    "🛶": "Canoe",
    "🚤": "Speedboat",
    "🛳️": "Passenger Ship",
    "⛴️": "Ferry",
    "🛥️": "Motor Boat",
    "🚢": "Ship",
    "✈️": "Aeroplane",
    "🛩️": "Small Aeroplane",
    "🛫": "Aeroplane Departure",
    "🛬": "Aeroplane Arrival",
    "💺": "Seat",
    "🚁": "Helicopter",
    "🚟": "Suspension Railway",
    "🚠": "Mountain Cableway",
    "🚡": "Aerial Tramway",
    "🛰️": "Satellite",
    "🚀": "Rocket",
    "🛸": "Flying Saucer",
    "🛎️": "Bellhop Bell",
    "🧳": "Luggage",
    "⌛": "Hourglass Done",
    "⏳": "Hourglass Not Done",
    "⌚": "Watch",
    "⏰": "Alarm Clock",
    "⏱️": "Stopwatch",
    "⏲️": "Timer Clock",
    "🕰️": "Mantelpiece Clock",
    "🕛": "Twelve O’Clock",
    "🕧": "Twelve-Thirty",
    "🕐": "One O’Clock",
    "🕜": "One-Thirty",
    "🕑": "Two O’Clock",
    "🕝": "Two-Thirty",
    "🕒": "Three O’Clock",
    "🕞": "Three-Thirty",
    "🕓": "Four O’Clock",
    "🕟": "Four-Thirty",
    "🕔": "Five O’Clock",
    "🕠": "Five-Thirty",
    "🕕": "Six O’Clock",
    "🕡": "Six-Thirty",
    "🕖": "Seven O’Clock",
    "🕢": "Seven-Thirty",
    "🕗": "Eight O’Clock",
    "🕣": "Eight-Thirty",
    "🕘": "Nine O’Clock",
    "🕤": "Nine-Thirty",
    "🕙": "Ten O’Clock",
    "🕥": "Ten-Thirty",
    "🕚": "Eleven O’Clock",
    "🕦": "Eleven-Thirty",
    "🌑": "New Moon",
    "🌒": "Waxing Crescent Moon",
    "🌓": "First Quarter Moon",
    "🌔": "Waxing Gibbous Moon",
    "🌕": "Full Moon",
    "🌖": "Waning Gibbous Moon",
    "🌗": "Last Quarter Moon",
    "🌘": "Waning Crescent Moon",
    "🌙": "Crescent Moon",
    "🌚": "New Moon Face",
    "🌛": "First Quarter Moon Face",
    "🌜": "Last Quarter Moon Face",
    "🌡️": "Thermometer",
    "☀️": "Sun",
    "🌝": "Full Moon Face",
    "🌞": "Sun with Face",
    "⭐": "Star",
    "🌟": "Glowing Star",
    "🌠": "Shooting Star",
    "☁️": "Cloud",
    "⛅": "Sun Behind Cloud",
    "⛈️": "Cloud with Lightning and Rain",
    "🌤️": "Sun Behind Small Cloud",
    "🌥️": "Sun Behind Large Cloud",
    "🌦️": "Sun Behind Rain Cloud",
    "🌧️": "Cloud with Rain",
    "🌨️": "Cloud with Snow",
    "🌩️": "Cloud with Lightning",
    "🌪️": "Tornado",
    "🌫️": "Fog",
    "🌬️": "Wind Face",
    "🌀": "Cyclone",
    "🌈": "Rainbow",
    "🌂": "Closed Umbrella",
    "☂️": "Umbrella",
    "☔": "Umbrella with Rain Drops",
    "⛱️": "Umbrella on Ground",
    "⚡": "High Voltage",
    "❄️": "Snowflake",
    "☃️": "Snowman",
    "⛄": "Snowman Without Snow",
    "☄️": "Comet",
    "🔥": "Fire",
    "💧": "Droplet",
    "🌊": "Water Wave",
    "🎃": "Jack-O-Lantern",
    "🎄": "Christmas Tree",
    "🎆": "Fireworks",
    "🎇": "Sparkler",
    "✨": "Sparkles",
    "🎈": "Balloon",
    "🎉": "Party Popper",
    "🎊": "Confetti Ball",
    "🎋": "Tanabata Tree",
    "🎍": "Pine Decoration",
    "🎎": "Japanese Dolls",
    "🎏": "Carp Streamer",
    "🎐": "Wind Chime",
    "🎑": "Moon Viewing Ceremony",
    "🧧": "Red Envelope",
    "🎀": "Ribbon",
    "🎁": "Wrapped Gift",
    "🎗️": "Reminder Ribbon",
    "🎟️": "Admission Tickets",
    "🎫": "Ticket",
    "🎖️": "Military Medal",
    "🏆": "Trophy",
    "🏅": "Sports Medal",
    "🥇": "First Place Medal",
    "🥈": "Second Place Medal",
    "🥉": "Third Place Medal",
    "⚽": "Soccer Ball",
    "⚾": "Baseball",
    "🥎": "Softball",
    "🏀": "Basketball",
    "🏐": "Volleyball",
    "🏈": "American Football",
    "🏉": "Rugby Football",
    "🎾": "Tennis",
    "🥏": "Flying Disc",
    "🎳": "Bowling",
    "🏏": "Cricket Game",
    "🏑": "Field Hockey",
    "🏒": "Ice Hockey",
    "🥍": "Lacrosse",
    "🏓": "Ping Pong",
    "🏸": "Badminton",
    "🥊": "Boxing Glove",
    "🥋": "Martial Arts Uniform",
    "🥅": "Goal Net",
    "⛳": "Flag in Hole",
    "⛸️": "Ice Skate",
    "🎣": "Fishing Pole",
    "🎽": "Running Shirt",
    "🎿": "Ski",
    "🛷": "Sled",
    "🥌": "Curling Stone",
    "🎯": "Direct Hit",
    "🪀": "Yo-Yo",
    "🪁": "Kite",
    "🎱": "Pool 8 Ball",
    "🔮": "Crystal Ball",
    "🧿": "Nazar Amulet",
    "🎮": "Video Game",
    "🕹️": "Joystick",
    "🎰": "Slot Machine",
    "🎲": "Game Die",
    "🧩": "Puzzle Piece",
    "🧸": "Teddy Bear",
    "🪅": "Pinata",
    "🪆": "Nesting Dolls",
    "♠️": "Spade Suit",
    "♥️": "Heart Suit",
    "♦️": "Diamond Suit",
    "♣️": "Club Suit",
    "♟️": "Chess Pawn",
    "🃏": "Joker",
    "🀄": "Mahjong Red Dragon",
    "🎴": "Flower Playing Cards",
    "🎭": "Performing Arts",
    "🖼️": "Framed Picture",
    "🎨": "Artist Palette",
    "🧵": "Thread",
    "🪡": "Needle",
    "🧶": "Yarn",
    "🪢": "Knot",
    "👓": "Glasses",
    "🕶️": "Sunglasses",
    "🥽": "Goggles",
    "🥼": "Lab Coat",
    "🦺": "Safety Vest",
    "👔": "Necktie",
    "👕": "Shirt",
    "👖": "Jeans",
    "🧣": "Scarf",
    "🧤": "Gloves",
    "🧥": "Coat",
    "🧦": "Socks",
    "👗": "Dress",
    "👘": "Kimono",
    "🥻": "Sari",
    "🩱": "One-Piece Swimsuit",
    "🩲": "Briefs",
    "🩳": "Shorts",
    "👙": "Bikini",
    "👚": "Woman’s Clothes",
    "👛": "Purse",
    "👜": "Handbag",
    "👝": "Clutch Bag",
    "🛍️": "Shopping Bags",
    "🎒": "Backpack",
    "🩴": "Thong Sandal",
    "👞": "Man’s Shoe",
    "👟": "Running Shoe",
    "🥾": "Hiking Boot",
    "🥿": "Flat Shoe",
    "👠": "High-Heeled Shoe",
    "👡": "Woman’s Sandal",
    "🩰": "Ballet Shoes",
    "👢": "Woman’s Boot",
    "👑": "Crown",
    "👒": "Woman’s Hat",
    "🎩": "Top Hat",
    "🎓": "Graduation Cap",
    "🧢": "Billed Cap",
    "⛑️": "Rescue Worker’s Helmet",
    "📿": "Prayer Beads",
    "💄": "Lipstick",
    "💍": "Ring",
    "💎": "Gem Stone",
    "🐵": "Monkey Face",
    "🐒": "Monkey",
    "🦍": "Gorilla",
    "🦧": "Orangutan",
    "🐶": "Dog Face",
    "🐕": "Dog",
    "🦮": "Guide Dog",
    "🐕‍🦺": "Therapy Dog",
    "🐩": "Poodle",
    "🐺": "Wolf",
    "🦊": "Fox",
    "🦝": "Raccoon",
    "🐱": "Cat Face",
    "🐈": "Cat",
    "🐈‍⬛": "Black Cat",
    "🦁": "Lion",
    "🐯": "Tiger Face",
    "🐅": "Tiger",
    "🐆": "Leopard",
    "🐴": "Horse Face",
    "🐎": "Horse",
    "🦄": "Unicorn",
    "🦓": "Zebra",
    "🦌": "Deer",
    "🦬": "Bison",
    "🐮": "Cow Face",
    "🐂": "Ox",
    "🐃": "Water Buffalo",
    "🐄": "Cow",
    "🐷": "Pig Face",
    "🐖": "Pig",
    "🐗": "Boar",
    "🐽": "Pig Nose",
    "🐏": "Ram",
    "🐑": "Ewe",
    "🐐": "Goat",
    "🐪": "Camel",
    "🐫": "Two-Hump Camel",
    "🦙": "Llama",
    "🦒": "Giraffe",
    "🐘": "Elephant",
    "🦏": "Rhinoceros",
    "🦛": "Hippopotamus",
    "🐭": "Mouse Face",
    "🐁": "Mouse",
    "🐀": "Rat",
    "🐹": "Hamster Face",
    "🐰": "Rabbit Face",
    "🐇": "Rabbit",
    "🐿️": "Chipmunk",
    "🦔": "Hedgehog",
    "🦇": "Bat",
    "🐻": "Bear",
    "🐨": "Koala",
    "🐼": "Panda",
    "🦥": "Sloth",
    "🦦": "Otter",
    "🦨": "Skunk",
    "🦘": "Kangaroo",
    "🦡": "Badger",
    "🐾": "Paw Prints",
    "🦃": "Turkey",
    "🐔": "Chicken",
    "🐓": "Rooster",
    "🐣": "Hatching Chick",
    "🐤": "Baby Chick",
    "🐥": "Front-Facing Baby Chick",
    "🐦": "Bird",
    "🐧": "Penguin",
    "🕊️": "Dove",
    "🦅": "Eagle",
    "🦆": "Duck",
    "🦢": "Swan",
    "🦉": "Owl",
    "🦩": "Flamingo",
    "🦚": "Peacock",
    "🦜": "Parrot",
    "🐸": "Frog",
    "🐊": "Crocodile",
    "🐢": "Turtle",
    "🦎": "Lizard",
    "🐍": "Snake",
    "🐲": "Dragon Face",
    "🐉": "Dragon",
    "🦕": "Sauropod",
    "🦖": "T-Rex",
    "🐳": "Spouting Whale",
    "🐋": "Whale",
    "🐬": "Dolphin",
    "🦭": "Seal",
    "🐟": "Fish",
    "🐠": "Tropical Fish",
    "🐡": "Blowfish",
    "🦈": "Shark",
    "🐙": "Octopus",
    "🐚": "Spiral Shell",
    "🐌": "Snail",
    "🦋": "Butterfly",
    "🐛": "Bug",
    "🐜": "Ant",
    "🐝": "Honeybee",
    "🐞": "Lady Beetle",
    "🦗": "Cricket",
    "🕷️": "Spider",
    "🕸️": "Spider Web",
    "🦂": "Scorpion",
    "🦟": "Mosquito",
    "🪰": "Fly",
    "🪱": "Worm",
    "🦠": "Microbe",
    "💐": "Bouquet",
    "🌸": "Cherry Blossom",
    "💮": "White Flower",
    "🏵️": "Rosette",
    "🌹": "Rose",
    "🥀": "Wilted Flower",
    "🌺": "Hibiscus",
    "🌻": "Sunflower",
    "🌼": "Blossom",
    "🌷": "Tulip",
    "🌱": "Seedling",
    "🪴": "Potted Plant",
    "🌲": "Evergreen Tree",
    "🌳": "Deciduous Tree",
    "🌴": "Palm Tree",
    "🌵": "Cactus",
    "🌾": "Sheaf of Rice",
    "🌿": "Herb",
    "☘️": "Shamrock",
    "🍀": "Four Leaf Clover",
    "🍁": "Maple Leaf",
    "🍂": "Fallen Leaf",
    "🍃": "Leaf Fluttering in Wind",
    "🍄": "Mushroom",
    "🌰": "Chestnut",
    "🦀": "Crab",
    "🦞": "Lobster",
    "🦐": "Shrimp",
    "🦑": "Squid",
    "🌍": "Earth Globe Europe-Africa",
    "🌎": "Earth Globe Americas",
    "🌏": "Earth Globe Asia-Australia",
    "🌐": "Globe with Meridians",
    "🗺️": "World Map",
    "🗾": "Map of Japan",
    "🧭": "Compass",
    "🏔️": "Snow-Capped Mountain",
    "⛰️": "Mountain",
    "🌋": "Volcano",
    "🗻": "Mount Fuji",
    "🏕️": "Camping",
    "🏖️": "Beach with Umbrella",
    "🏜️": "Desert",
    "🏝️": "Desert Island",
    "🏞️": "National Park",
    "🏟️": "Stadium",
    "🏛️": "Classical Building",
    "🏗️": "Building Construction",
    "🧱": "Brick",
    "🏘️": "Houses",
    "🏚️": "Derelict House",
    "🏠": "House",
    "🏡": "House with Garden",
    "🏢": "Office Building",
    "🏣": "Japanese Post Office",
    "🏤": "Post Office",
    "🏥": "Hospital",
    "🏦": "Bank",
    "🏨": "Hotel",
    "🏩": "Love Hotel",
    "🏪": "Convenience Store",
    "🏫": "School",
    "🏬": "Department Store",
    "🏭": "Factory",
    "🏯": "Japanese Castle",
    "🏰": "Castle",
    "💒": "Wedding",
    "🗼": "Tokyo Tower",
    "🗽": "Statue of Liberty",
    "⛪": "Church",
    "🕌": "Mosque",
    "🕍": "Synagogue",
    "⛩️": "Shinto Shrine",
    "🕋": "Kaaba",
    "⛲": "Fountain",
    "⛺": "Tent",
    "🌁": "Foggy",
    "🌃": "Night with Stars",
    "🏙️": "Cityscape",
    "🌄": "Sunrise Over Mountains",
    "🌅": "Sunrise",
    "🌆": "Cityscape at Dusk",
    "🌇": "Sunset",
    "🌉": "Bridge at Night",
    "♨️": "Hot Springs",
    "🎠": "Carousel Horse",
    "🎡": "Ferris Wheel",
    "🎢": "Roller Coaster",
    "💈": "Barber Pole",
    "🎪": "Circus Tent",
    "🚂": "Locomotive",
    "🚃": "Railway Car",
    "🚄": "High-Speed Train",
    "🚅": "Bullet Train",
    "🚆": "Train",
    "🚇": "Metro",
    "🚈": "Light Rail",
    "🚉": "Station",
    "🚊": "Tram",
    "🚝": "Monorail",
    "🚞": "Mountain Railway",
    "🚋": "Tram Car",
    "🚌": "Bus",
    "🚍": "Oncoming Bus",
    "🚎": "Trolleybus",
    "🚐": "Minibus",
    "🚑": "Ambulance",
    "🚒": "Fire Engine",
    "🚓": "Police Car",
    "🚔": "Oncoming Police Car",
    "🚕": "Taxi",
    "🚖": "Oncoming Taxi",
    "🚗": "Automobile",
    "🚘": "Oncoming Automobile",
    "🚙": "Sport Utility Vehicle",
    "🚚": "Delivery Truck",
    "🚛": "Articulated Lorry",
    "🚜": "Tractor",
    "🏎️": "Racing Car",
    "🏍️": "Motorcycle",
    "🛵": "Motor Scooter",
    "🦽": "Manual Wheelchair",
    "🦼": "Motorized Wheelchair",
    "🛺": "Auto Rickshaw",
    "🚲": "Bicycle",
    "🛴": "Kick Scooter",
    "🛹": "Skateboard",
    "🛼": "Roller Skate",
    "🚏": "Bus Stop",
    "🛣️": "Motorway",
    "🛤️": "Railway Track",
    "🛢️": "Oil Drum",
    "⛽": "Fuel Pump",
    "🚨": "Police Car Light",
    "🚥": "Horizontal Traffic Light",
    "🚦": "Vertical Traffic Light",
    "🛑": "Stop Sign",
    "🚧": "Construction",
    "⚓": "Anchor",
    "⛵": "Sailboat",
    "🛶": "Canoe",
    "🚤": "Speedboat",
    "🛳️": "Passenger Ship",
    "⛴️": "Ferry",
    "🛥️": "Motor Boat",
    "🚢": "Ship",
    "✈️": "Aeroplane",
    "🛩️": "Small Aeroplane",
    "🛫": "Aeroplane Departure",
    "🛬": "Aeroplane Arrival",
    "💺": "Seat",
    "🚁": "Helicopter",
    "🚟": "Suspension Railway",
    "🚠": "Mountain Cableway",
    "🚡": "Aerial Tramway",
    "🛰️": "Satellite",
    "🚀": "Rocket",
    "🛸": "Flying Saucer",
    "🛎️": "Bellhop Bell",
    "🧳": "Luggage",
    "⌛": "Hourglass Done",
    "⏳": "Hourglass Not Done",
    "⌚": "Watch",
    "⏰": "Alarm Clock",
    "⏱️": "Stopwatch",
    "⏲️": "Timer Clock",
    "🕰️": "Mantelpiece Clock",
    "🕛": "Twelve O’Clock",
    "🕧": "Twelve-Thirty",
    "🕐": "One O’Clock",
    "🕜": "One-Thirty",
    "🕑": "Two O’Clock",
    "🕝": "Two-Thirty",
    "🕒": "Three O’Clock",
    "🕞": "Three-Thirty",
    "🕓": "Four O’Clock",
    "🕟": "Four-Thirty",
    "🕔": "Five O’Clock",
    "🕠": "Five-Thirty",
    "🕕": "Six O’Clock",
    "🕡": "Six-Thirty",
    "🕖": "Seven O’Clock",
    "🕢": "Seven-Thirty",
    "🕗": "Eight O’Clock",
    "🕣": "Eight-Thirty",
    "🕘": "Nine O’Clock",
    "🕤": "Nine-Thirty",
    "🕙": "Ten O’Clock",
    "🕥": "Ten-Thirty",
    "🕚": "Eleven O’Clock",
    "🕦": "Eleven-Thirty",
    "🌑": "New Moon",
    "🌒": "Waxing Crescent Moon",
    "🌓": "First Quarter Moon",
    "🌔": "Waxing Gibbous Moon",
    "🌕": "Full Moon",
    "🌖": "Waning Gibbous Moon",
    "🌗": "Last Quarter Moon",
    "🌘": "Waning Crescent Moon",
    "🌙": "Crescent Moon",
    "🌚": "New Moon Face",
    "🌛": "First Quarter Moon Face",
    "🌜": "Last Quarter Moon Face",
    "🌡️": "Thermometer",
    "☀️": "Sun",
    "🌝": "Full Moon Face",
    "🌞": "Sun with Face",
    "⭐": "Star",
    "🌟": "Glowing Star",
    "🌠": "Shooting Star",
    "☁️": "Cloud",
    "⛅": "Sun Behind Cloud",
    "⛈️": "Cloud with Lightning and Rain",
    "🌤️": "Sun Behind Small Cloud",
    "🌥️": "Sun Behind Large Cloud",
    "🌦️": "Sun Behind Rain Cloud",
    "🌧️": "Cloud with Rain",
    "🌨️": "Cloud with Snow",
    "🌩️": "Cloud with Lightning",
    "🌪️": "Tornado",
    "🌫️": "Fog",
    "🌬️": "Wind Face",
    "🌀": "Cyclone",
    "🌈": "Rainbow",
    "🌂": "Closed Umbrella",
    "☂️": "Umbrella",
    "☔": "Umbrella with Rain Drops",
    "⛱️": "Umbrella on Ground",
    "⚡": "High Voltage",
    "❄️": "Snowflake",
    "☃️": "Snowman",
    "⛄": "Snowman Without Snow",
    "☄️": "Comet",
    "🔥": "Fire",
    "💧": "Droplet",
    "🌊": "Water Wave",
    };